export const IMG_BANNER = require('./images/Banner.png')
export const IMG_AVT1 = require('./images/img_avatar.png')
export const IMG_AVT2 = require('./images/img_avatar2.png')
export const IMG_AVT3 = require('./images/img_avatar3.png')
export const IMG_OVAL = require('./images/Oval.png')


export const IC_EMAIL = require('./icons/ic_email.png')
export const IC_FILE = require('./icons/ic_file.png')
export const IC_MSG = require('./icons/ic_msg.png')
export const IC_PEOPLE = require('./icons/ic_people.png')
export const IC_PHONE_DARK = require('./icons/ic_phone_dark.png')
export const IC_PHONE = require('./icons/ic_phone.png')
export const IC_PROFIlE = require('./icons/ic_profile.png')
export const IC_QUESTION = require('./icons/ic_question.png')
export const IC_SEARCH = require('./icons/ic_search.png')
export const IC_ADD = require('./icons/ic_add.png')
